---
- name: Create EC2 instance
  hosts: localhost
  gather_facts: False
  vars:
    ansible_python_interpreter: /home/ubuntu/ansible_ec2/.env/bin/python
  tasks:
    - name: Launch a new EC2 instance
      amazon.aws.ec2_instance:
        aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
        aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
        key_name: key_pub_ec2
        instance_type: t3.nano
        image_id: ami-0506d6d51f1916a96
        wait: yes
        count: 1
        tags:
          Name: Ansible_EC2
        region: eu-north-1
      register: ec2


    
