---
- name: Stop an EC2 instance
  hosts: localhost
  gather_facts: False
  vars:
    ansible_python_interpreter: /home/ubuntu/ansible_ec2/.env/bin/python
    aws_access_key: "{{ lookup('env', 'AWS_ACCESS_KEY') }}"
    aws_secret_key: "{{ lookup('env', 'AWS_SECRET_KEY') }}"
    region: "eu-north-1"
    instance_id: "i-080540cdbfc7633e7"
  tasks:
    - name: Stop instance
      amazon.aws.ec2_instance:
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ region }}"
        instance_ids:
          - "{{ instance_id }}"
        state: stopped

